# Generated by Django 4.2.19 on 2025-11-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="user", new_name="author",
        ),
    ]
