# Generated by Django 4.2.19 on 2025-12-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
